server:
  port: 8762

spring:
  application:
    name: eureka

# 服务注册
eureka:
  # 实例设置
  instance:
    # 实例主机名
    hostname: localhost
  client:
    ## 由于注册中心的职责就是维护服务实例，它不需要去检索服务，所以设置为false
    fetch-registry: false
    ## 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己（注册中心集群时开启）
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


